#!/bin/bash
set -e

seconds=0
is_stopwatch=false
while [ $# -gt 0 ]; do
  case "$1" in
  -s|--sec)
    seconds=$2
    ;;
  -m|--min)
    seconds=$(($2*60))
    ;;
  -w|--stopwatch)
    is_stopwatch=true
    ;;
  -h|--help)
    echo "Run a timer or stopwatch.

gh timer [units] [number]

[units]
  -s, --sec : seconds 
  -m, --min : minutes

Examples:

gh timer --sec 30
    run stopwatch for 30 seconds

gh timer --min 5
    run stopwatch for 5 minutes"
    exit 0
    ;;
  esac
  shift
done

show_clock () {
    local hours=$1
    local minutes=$2
    local seconds=$3
    echo -ne "$hours:$minutes:$seconds\r"
}

start_date=$(date +%s)
end_date=$(date --date="+$seconds seconds" +%s)

while ! [ $(( $(date +%s) - $start_date )) -ge $seconds ]; do
    if [ "$is_stopwatch" = true ] ; then
        show_clock "$(date -u --date @$(( $(date +%s) - $start_date )) +%H)" "$(date -u --date @$(( $(date +%s) - $start_date )) +%M)" "$(date -u --date @$(( $(date +%s) - $start_date )) +%S)"
    else
        show_clock "$(date -u --date @$(( $end_date - $(date +%s) )) +%H)" "$(date -u --date @$(( $end_date - $(date +%s) )) +%M)" "$(date -u --date @$(( $end_date - $(date +%s) )) +%S)"
    fi
done
